### ISSUE TITLE
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""

### ISSUE THREAD

**Issue by mschaaf** [evuez/slate#2]
Getting the following error on installing via: stack install slate

```
 Downloaded lts-11.5 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

I am on ubuntu 18.04 with stack version Version 1.5.1 x86_64

**Comment by mschaaf** [comment]
I will close because upgrading to the latest version (1.6.5) resolves the issue.

**Comment by evuez** [comment]
Thanks, I [added a note to the README](https://github.com/evuez/slate/commit/8c8b80c07333d23a5569cc8eaabf0de918ddb6db) :)
